services:
  - type: web
    name: farmtrade-backend
    env: docker
    plan: free
    branch: main
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-spring-salad-aivnukkz-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_frDvEBU4V5Wm
      - key: JWT_SECRET
        generateValue: true
